version: '3'
services:
  database:
    image: postgres:13
    restart: always
    container_name: e-connest-db-dev
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DB}
    ports:
      - '5432:5432'
    volumes:
      - e-connest-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: always
    container_name: e-connest-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
volumes:
  e-connest-data:
    external: true
  redis-data:
