name: Run Tests

on: [pull_request]  # En cada PR

jobs:
  build:
    runs-on: ubuntu-latest  # Plataforma del runner

    steps:
    - name: Checkout código
      uses: actions/checkout@v2  # Clona el repositorio

    - name: Instalar dependencias
      run: npm install  # Instala las npm dependencies

    - name: Ejecutar pruebas
      run: npm run test  # Ejecuta las pruebas
